name: em16
favicon: null
layout_spectrum: 0.38322
typography_spectrum: 0.5656174118630588
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e5a5a6'
    - '#d7888e'
    - '#dcd9d4'
    - '#883d42'
    - '#9c5459'
  brandStrength: 0.48907687282189727
  lightness: 0.01982802082784474
  saturation: 0.3285607257857919
  rhythmicContrast: 0.6407295914832503
purpose: []
