typography_spectrum: 0.54295
color:
  brandColors:
    - '#e5a5a6'
    - '#d7888e'
    - '#dcd9d4'
    - '#883d42'
    - '#9c5459'
  brandStrength: 1
  lightness: 1
  saturation: 0.3285607257857919
  rhythmicContrast: 0
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.3734
analytics:
  google: null
  facebook: null
  twitter: null
name: em16
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: GRAPHIC DESIGN & ILLUSTRATION
description: emily north
purpose: []
