layout_spectrum: 0.07920966437086463
typography_spectrum: 0.1463405042886734
color:
  brandColors:
    - '#FFFFFF'
    - '#CCCCCC'
    - '#999999'
    - '#4D4D4D'
    - '#333333'
  brandStrength: 0.38391163712367415
  lightness: 0.9579798518680036
  saturation: 0.4362486070021987
  rhythmicContrast: 0.5539346146397293
opengraph:
  image: null
  type: null
  appId: null
analytics:
  google: null
  facebook: null
  twitter: null
name: em16
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: GRAPHIC DESIGN & ILLUSTRATION
description: emily north
purpose: []
