name: em16
favicon: null
layout_spectrum: 0.88811
typography_spectrum: 0.54295
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e5a5a6'
    - '#d7888e'
    - '#dcd9d4'
    - '#883d42'
    - '#9c5459'
  brandStrength: 1
  lightness: 1
  saturation: 0.3285607257857919
  rhythmicContrast: 0
purpose: []
